name: Criterion Unit Tests

on:
  push:
    branches: [ "criterion-tests" ]
  pull_request:
    branches: [ "criterion-tests" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Update version
      run: sudo apt-get update
    - name: Install Homebrew
      run: sudo apt-get install build-essential procps curl file git
    - name: Install brew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: Install Criterion
      run: brew install snaipe/soft/criterion
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
