name: Criterion Unit Tests

on:
  push:
    branches: [ "criterion-tests" ]
  pull_request:
    branches: [ "criterion-tests" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Add apt repository
      run: sudo add-apt-repository ppa:snaipewastaken/ppa
    - name: Apt update
      run: sudo apt-get update
    - name: Install criterion
      run: sudo apt-get install criterion-dev
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
